version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose: 
      - 5000
    volumes:
      - ./backend:/usr/src/app
    environment: 
      - FLASK_ENV=production
      - FLASK_APP=view.py
  my-app:
    build: ./my-app
    ports:
      - 3000:80
    volumes:
      - ./my-app:/app
      - ./app/node_modules
    depends_on: 
      - backend
