version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    expose: 
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app
    environment: 
      - FLASK_ENV=development
      - FLASK_APP=view.py
      - FLASK_DEBUG=1
  my-app:
    build:  ./my-app
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./my-app/src:/usr/src/app/src
      - ./my-app/public:/usr/src/app/public
    links:
      - "backend:backend"
